spring:
  datasource:
    url: jdbc:mysql://localhost:3306/skill_up
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ehskfem1!

  jpa:
    hibernate:
      ddl-auto: update  # ?? update, create-drop ? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true